(RES) Restructured entire project. (MOD) Changed the file path in CMakeLists.txt to adapt the restructure. (ADD) Added Stack. (MOD) Enforced constructive operations of Array departed into Create,       Allocate, (Reallocate) and Release. (ADD) Added CharSeq. (MOD) Made CharSeq utilities virtual. (ADD) Added a new MagicMacro "naming(e, i)" in common.h. (MOD) Modified the definition of "apply". (ADD) Added a new MagicMacro "type(obj)" in common.h. (ADD) Added a new type declaration specifier "Var(T)". (DEL) Removed a type declaration specifier "String(T)". (ADD) Added a new type declaration specifier "virtual(funcdecl)". (ADD) Added a new macro __COMPOUND_STACK_MAXIMUM__.  Used by Stack. (ADD) Added a new interface implementer "LITERALISE" (ADD) Added a new interface implementer "CONSTRUCTOR" (ADD) Added a new interface implementer "DESTRUCTOR" (ADD) Added constructor_t.  Used for specifying custom constructor for an object. (ADD) Added a default construction handler "Constructor". (ADD) Added destructor_t.  Used for specifying custom destructor for an object. (ADD) Added a default destruction handler "Destructor". (ADD) Added File. (MOD) Modified the definition of Function. (ADD) Added a new operation for Function, "Overwrite". (ADD) Added a new operation utility for Function, "IsVariadic". (ADD) Added literalisation_t.  Used for specifying custom literalisation for an object. (IMP) Implemented literalisation_t into Memory. (MOD) Modified Object. (ADD) Added Builder.  Used to build objects with implementing Constructor and Destructor. (REN) Renamed UN... with CLEAR_... from "enum PEN_RENDER_HIGHLIGHT_METHOD" in pen.h. (ADD) Added definitions of __COMPOUND_STACK_MAXIMUM__ as 0x800000L in platform.h. (MOD) Modified macro error message in platform.h. (ADD) Added a new Status "Failure". (ADD) Added a new Status "InvalidSize". (ADD) Added a new Status "SourceNotAlive". (ADD) Added a new Status "StoreNotAlive". (REN) Renamed a Status "ArrayLengthError" with "InvalidArrayLength". (ADD) Added a new Status "ArrayIndexOutOfBound". (ADD) Added a new Status "RecursionTerminated". (DEL) Removed Status "RecreationOnInstanceStillAlive". (ADD) Added a new Status "UnavailableSource". (ADD) Added a new Status "UnavailableStore". (ADD) Added a new Status "StringConversionPrecisionError". (ADD) Added a new Status "UnsupportedEncoding". (ADD) Added a new Status "FunctionNotDeployed". (ADD) Added TimeZone. (ADD) Added TimeDate. (MOD) Enforced constructive operations of Var departed into Create,       Allocate, (Reallocate) and Release. (DEL) Removed a Var operation "Var_Assign".

diff --git a/preinstall b/preinstall
--- a/preinstall
+++ b/preinstall
@@ -1,35 +1,11 @@
 #!/bin/sh
 
-if [ "$(whoami)" != "root" ]; then
-  echo "The script require root privilege to execute properly.  Current identity: $(whoami)"
-  exit 1
-fi
-
-SRC="$PWD"
 DST=/usr/include/Compound
-set -- Array Paper Pen Render Status Var MemMan Stack Utils String Object
 
 # Create directory.
-if [ ! -d "$DST" ]; then
-  mkdir -pv "$DST"
-fi
+[ ! -d "$DST" ] && mkdir -pv "$DST"
 
-# Install project-like headers.
-while :; do  
-  p="$1"
-  if [ -z "$1" ]; then break; fi
-  
-  cd "$p" || exit 1
-  echo "$(date) >>> Installing $p"
-  cp -v include/*.h "$DST"
-  cd "$SRC" || exit 1
-  shift 1
-  echo
-done
+# Install headers.
+cp -v inc/* "$DST" || ( printf "\nPre-installation failed.\n" >&2 && exit 1 )
 
-# Install individual headers.
-cp -v "common.h" "const.h" "platform.h"\
-      "name.h" "namescope.h" "type.h" "catlog.h"\
-      "attr.h" "registry.h" "class.h" "function.h" "report.h" "$DST"
-
-printf "\nDone\n"
+printf "\nProcedure succeeded.\n"
